# Generated by Django 4.2.2 on 2023-06-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                default="click link above to read blogpost", max_length=255
            ),
        ),
    ]
