# Generated by Django 4.2.2 on 2023-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_author_bio_author_date_of_birth_alter_author_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="facebook_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="twitter_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
    ]
