# Generated by Django 4.2.2 on 2023-06-29 08:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_author_follows_alter_comment_post"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="author",
            managers=[
                ("objects", blog.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="author",
            name="username",
        ),
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
